import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";
import axios from "axios";
import Navbar from "../components/Navbar";
import Header from "../components/Header";

import Footer from "../components/Footer";

import Contact from "../components/Contact";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <Contact />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  return {
    props: {}, // will be passed to the page component as props
  };
}
